var userName = window.prompt("please enter your name: ");
var greetingParagraph = document.getElementById("greeting");
greetingParagraph.innerHTML += ", " + userName
var num1 = parseInt(window.prompt("Enter a nmeber: "))
var num2 = parseInt(window.prompt("Enter a nmeber: "))
var operand1 = document.getElementById("operand1");
var operand2 = document.getElementById("operand2");
operand1.innerHTML += num1;
operand2.innerHTML += num2;
var sum = num1 + num2
var difference = num1 - num2
var product = num1 * num2
var quotient = num1 / num2
var mod = num1 % num2
var ad = document.getElementById("addition")
ad.innerHTML = "The sum of " + num1 + " and " + num2 + " is " + sum;
var sub = document.getElementById("subtraction")
sub.innerHTML = "The difference between " + num1 + " and " + num2 + " is " + difference;
var mul = document.getElementById("multiplication")
mul.innerHTML = "the product of " + num1 + " and " + num2 + " is " + product;
var div = document.getElementById("division")
div.innerHTML = "The quotient of " + num1 + " and " + num2 + " is " + quotient;
var mod = document.getElementById("modulus")
mod.innerHTML = "The modulus of " + num1 + " and " + num2 + " is " + modulus;